### ISSUE TITLE
Angular 4 compatibility?

### ISSUE THREAD

**Issue by klihelp** [TheLarkInn/angular2-template-loader#65]

**Comment by JunkyDeLuxe** [comment]
Hello, I have a problem
`template: 'login.component.html',`

Result in my web page with webpack dev server
displays the string login.component.html instead of the real html template.

**Comment by JunkyDeLuxe** [comment]
Ok fixed with this one:
`templateUrl: './login.component.html'`

EDIT: Don't use the keepUrl option !

**Comment by alex88** [comment]
I have `templateUrl: './app.component.html'` and in my config:

```
        {
          test: /\.ts$/,
          loader: ['@ngtools/webpack', 'angular2-template-loader']
        },
        {
          test: /\.html$/,
          exclude: [
            path.join(process.cwd(), 'src/public/index.html')
          ],
          loader: 'html-loader'
        },
```

however I still don't see images being required by html-loader, could it be related to angular 4?

**Comment by ghost** [comment]
I'm using this with Angular 4 just fine.

Also, the readme does show the following:

```ts
@Component({
  selector: 'awesome-button',
  template: 'button.template.html',
  styles: ['button.style.css']
})
export class AwesomeButtonComponent { }
```

Which led me to make the same mistake as @JunkyDeLuxe at first.
